services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MarkFlat\MarkFlatEditor\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MarkFlat\MarkFlatEditor\Controller\AdminController:
        arguments:
            $adminPassword: '%mark_flat_editor.admin_password%'
        tags: ['controller.service_arguments']
